// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mypzfxfjihtlxvauufyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cHpmeGZqaWh0bHh2YXV1Znl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0OTY0MzgsImV4cCI6MjA1MjA3MjQzOH0.J-Ardw27WiIzEuZX74HP8JQt4Z3FM0Uaz7qX5ELvHDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);